### ISSUE TITLE
Bumping a Project that is already based on .NET 8 results in downgrade of 

### ISSUE THREAD

**Issue by pkunze** [martincostello/dotnet-bumper#106]
### Describe the bug

I tried bumbing a Project which was already based on .NET 8, referencing Packages with the exact 8.0.0 Version. 
It upgraded most packages correctly to the current 8.0.2 version but missed `Microsoft.EntityFrameworkCore` leaving it at 8.0.0
Therefore the project could no longer be build

### Steps To reproduce

Have a Project already using .NET 8 at exaclty v8.0.0
e.g.
```xml
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
```
then run `dotnet bumper .`

### Expected behaviour

I would have hoped for the tool to either do nothing or update all relevant packages consistently.

### Actual behaviour
See Screenshots.

### Screenshots

![image](https://github.com/martincostello/dotnet-bumper/assets/1416798/650d1b15-e516-44b0-af1b-35fef53c8618)
![image](https://github.com/martincostello/dotnet-bumper/assets/1416798/046304dd-43a8-4a70-be4a-7e2bdc4d650a)

### Additional context

I love the Project. It helps a lot and im glad i found your tweet recently. Let me know if i can help or provide further information.

**Comment by martincostello** [comment]
Thanks for reporting this issue.

This will have been missed because of the `.` at the end of this filter:

https://github.com/martincostello/dotnet-bumper/blob/ceb61706ba94a6fbf0071dae67b6c8f77c9a9baa/src/DotNetBumper.Core/BumperConfigurationProvider.cs#L28

**Comment by pkunze** [comment]
Do you want me to file a PR? I worked around this by running `dotnet outdated -u` before bumper BTW. So NBD.
