### ISSUE TITLE
DockerfileUpgrader uses case sensitive regex to match images

### ISSUE THREAD

**Issue by ign3u5** [martincostello/dotnet-bumper#42]
### Describe the bug

When an image is aliased using a lower case `as`, that reference is not updated to the desired version.

### Steps To reproduce

Create a Dockerfile containing the following
```dockerfile
FROM dotnet-6.0-sdk AS Build
FROM dotnet-6.0-sdk as base
```

Run `dotnet bumper .`. 

### Expected behaviour

```dockerfile
FROM dotnet-9.0-sdk AS Build
FROM dotnet-9.0-sdk as base
```

### Actual behaviour

```dockerfile
FROM dotnet-9.0-sdk AS Build
FROM dotnet-6.0-sdk as base 
```

### Additional context

This looks to be due to the Regex being used https://github.com/martincostello/dotnet-bumper/blob/6137591ec2c84bdb2b932909ac74a64ccaad4193/src/DotNetBumper.Core/Upgraders/DockerfileUpgrader.cs#L236.
As Docker specifies that their syntax is not case sensitive [here](https://docs.docker.com/engine/reference/builder/#format), I would suggest this could follow similar guidelines. 

Suggested fix: change the content of the GeneratedRegex attribute argument to:
```regex
^(?i)FROM(?-i) ((?<platform>--platform=[\$\w]+)\s)?(?<image>[\w\.\/\-]+)(:(?<tag>[\w\-\.]+))?(\s(?<name>(?i)AS(?-i) [\S]+))?$
```

**Comment by martincostello** [comment]
😅 - I did think about that yesterday, but then for some reason I thought Docker was case-sensitive and didn't have to worry about it...

**Comment by ign3u5** [comment]
Happy to add the fix unless you're already on it?

**Comment by martincostello** [comment]
Fix away!
