### ISSUE TITLE
Add FAQs document

### ISSUE THREAD

**Issue by martincostello** [martincostello/dotnet-bumper#57]
### Is your feature request related to a problem?

Add a _Frequently Asked Questions_ style document that explains what the tool can and can't do.

### Describe the solution you'd like

Some markdown documentation in the GitHub repository about the tool.

Optionally use [docfx](https://dotnet.github.io/docfx/) to create a GitHub Pages static site for the documentation.

**Comment by elovelan** [comment]
One FAQ that would be quite helpful is how this compares to the [Upgrade Assistant CLI](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant), besides being open source and including support for upgrading EFCore.
